### ISSUE TITLE
你好，获取验证码模块报错，测试环境为真机

### ISSUE THREAD

**Issue by dandingol03** [cheikh-wang/LazyWaimai-Android#1]
ResponseErrorProxy$1$1.call  (ResponseErrorProxy.java:62)
ResponseErrorProxy$1$1.call  (ResponseErrorProxy.java:95)
网络请求出现错误: ResponseError{status=400, message='其他错误'}

**Comment by cheikh-wang** [comment]
你好，是我用来发送验证码的平台的余额不足了，我现在已经充值了，你再试试，谢谢反馈！

在 2017-04-17 16:42:35，"biliKing" <notifications@github.com> 写道：


ResponseErrorProxy$1$1.call (ResponseErrorProxy.java:62)
ResponseErrorProxy$1$1.call (ResponseErrorProxy.java:95)
网络请求出现错误: ResponseError{status=400, message='其他错误'}

**Comment by Hawken94** [comment]
为什么我会收到你们的消息^_^

**Comment by dandingol03** [comment]
能注册了，谢谢
