### ISSUE TITLE
大神你好，想请问你安卓端连接API的问题

### ISSUE THREAD

**Issue by livixfree** [cheikh-wang/LazyWaimai-Android#19]
大神你好呀，我是正在学安卓的小白，不好意思打扰你了。。web端和Api端我已经按你说的配置好了，web和Api运行正常，安卓端在电脑上用第三方模拟器运行，安卓端修改成本地url（"https://192.168.1.7/LazyWaimai-Api/web/"）后，（模拟器的浏览器可以访问这个url），会报出"网络请求出现错误"，（模拟器的浏览器可以访问这个url），请问该如何连接Api端？

**Comment by cheikh-wang** [comment]
试试如下的地址：
```
public static final String SERVER_URL = "http://192.168.1.7/LazyWaimai-Api/web/v1/";
```

**Comment by livixfree** [comment]
可以了，连接没问题，谢谢大神！
