### ISSUE TITLE
关于注入的问题

### ISSUE THREAD

**Issue by dandingol03** [cheikh-wang/LazyWaimai-Android#2]
hi
在创建BusinessController的实例时依赖了RestApiClient，可是我没明白RestApiClient是怎么创建实例的

**Comment by cheikh-wang** [comment]
是使用dagger2进行依赖注入的，RestApiClient实例创建的地方：[NetworkProvider.java](https://github.com/cheikh-wang/LazyWaimai-Android/blob/master/app/src/main/java/com/cheikh/lazywaimai/module/library/NetworkProvider.java)

**Comment by dandingol03** [comment]
额，找到了谢谢
