### ISSUE TITLE
云之讯无法使用问题

### ISSUE THREAD

**Issue by livixfree** [cheikh-wang/LazyWaimai-Android#20]
大神你好呀，有个问题打扰一下。七牛和云之讯按照要求配置了，七牛可以使用，但用云之讯获取验证码报出系统内部错误，我排查不出原因，有空的话可以解答一下吗(╥╯^╰╥)

**Comment by cheikh-wang** [comment]
具体的错误信息贴上来看看

**Comment by livixfree** [comment]
谢谢回复，我今天排查出问题了 在云之讯上新建应用和模板就解决问题了ヾ(✿ﾟ▽ﾟ)ノ

**Comment by cheikh-wang** [comment]
ok
