### ISSUE TITLE
想接着你这个接着开发，可是有的不明白，能否指点一下

### ISSUE THREAD

**Issue by thinkdai** [cheikh-wang/LazyWaimai-Android#3]
想接着你这个接着开发，可是有的不明白，能否指点一下

**Comment by 9ouhao** [comment]
你好，我对这个应用有点研究，你有什么不明白的地方，可以和我交流一下。

**Comment by thinkdai** [comment]
这个是mvp架构的，以前没有研究过，我想修改主界面却无从下手，看了源代码几天，还没有结果，主要想改成像美团首页那样，带banner，带菜单什么的，可否加我QQ：53479990好方便请教
